require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
    #- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'lib/rammus/protocol/*'
    - 'generate_protocol.rb'
    - 'spec/support/test_server.rb' # TODO cut down on noise

# TODO: cutting down on noise
Naming/AccessorMethodName:
  Enabled: false

# TODO: cutting down on noise
Naming/PredicateName:
  Enabled: false

# TODO: cut down on noise
Style/ExpandPathArguments:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/Semicolon:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  Exclude:
    - 'lib/rammus/protocol_logger.rb'

Layout/RescueEnsureAlignment:
  Exclude:
    - 'lib/rammus/web_socket_client.rb'

Layout/ArgumentAlignment:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'lib/rammus/web_socket_client.rb'
    - 'lib/rammus/lifecycle_watcher.rb'

Style/LambdaCall:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/BlockComments:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - 'lib/rammus/mouse.rb'
    - 'lib/rammus/touchscreen.rb'

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/RedundantBlockCall:
  Enabled: false

#Naming/PredicateName:
#  # Method define macros for dynamically generated method.
#  MethodDefinitionMacros:
#    - define_method
#    - define_singleton_method
#    - def_node_matcher
#    - def_node_search
#
#Style/FormatStringToken:
#  # Because we parse a lot of source codes from strings. Percent arrays
#  # look like unannotated format string tokens to this cop.
#  Exclude:
#    - spec/**/*
#
#Style/IpAddresses:
#  # The test for this cop includes strings that would cause offenses
#  Exclude:
#  - spec/rubocop/cop/style/ip_addresses_spec.rb
#
#Layout/EndOfLine:
#  EnforcedStyle: lf
#
#Layout/ClassStructure:
#  Enabled: true
#  Categories:
#    module_inclusion:
#      - include
#      - prepend
#      - extend
#  ExpectedOrder:
#      - module_inclusion
#      - constants
#      - public_class_methods
#      - initializer
#      - instance_methods
#      - protected_methods
#      - private_methods
#
## Trailing white space is meaningful in code examples
#Layout/TrailingWhitespace:
#  AllowInHeredoc: true
#
#Lint/AmbiguousBlockAssociation:
#  Exclude:
#    - 'spec/**/*.rb'
#
#Layout/HashAlignment:
#  EnforcedHashRocketStyle:
#    - key
#    - table
#  EnforcedColonStyle:
#    - key
#    - table
#
#Lint/InterpolationCheck:
#  Exclude:
#    - 'spec/**/*.rb'
#
#Lint/UselessAccessModifier:
#  MethodCreatingMethods:
#    - 'def_matcher'
#    - 'def_node_matcher'
#
#Lint/BooleanSymbol:
#  Enabled: false
#
#Metrics/BlockLength:
#  Exclude:
#    - 'Rakefile'
#    - '**/*.rake'
#    - 'spec/**/*.rb'
#    - '**/*.gemspec'
#
#Metrics/ClassLength:
#  Exclude:
#    - lib/rubocop/config_obsoletion.rb
#
#Metrics/ModuleLength:
#  Exclude:
#    - 'spec/**/*.rb'
#
#RSpec/FilePath:
#  Exclude:
#    - spec/rubocop/formatter/junit_formatter_spec.rb
#
#RSpec/PredicateMatcher:
#  EnforcedStyle: explicit
#
#RSpec/MessageSpies:
#  EnforcedStyle: receive
#
#RSpec/NestedGroups:
#  Max: 7
