language: ruby

rvm:
  - 2.6

gemfile:
  - Gemfile

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - gem update --system
  - gem install bundler

script: "bundle exec rspec"
