module Rammus
  module Protocol
      autoload :Accessibility, "rammus/protocol/accessibility.rb"
      autoload :Animation, "rammus/protocol/animation.rb"
      autoload :ApplicationCache, "rammus/protocol/application_cache.rb"
      autoload :Audits, "rammus/protocol/audits.rb"
      autoload :Browser, "rammus/protocol/browser.rb"
      autoload :CSS, "rammus/protocol/css.rb"
      autoload :CacheStorage, "rammus/protocol/cache_storage.rb"
      autoload :Cast, "rammus/protocol/cast.rb"
      autoload :DOM, "rammus/protocol/dom.rb"
      autoload :DOMDebugger, "rammus/protocol/dom_debugger.rb"
      autoload :DOMSnapshot, "rammus/protocol/dom_snapshot.rb"
      autoload :DOMStorage, "rammus/protocol/dom_storage.rb"
      autoload :Database, "rammus/protocol/database.rb"
      autoload :DeviceOrientation, "rammus/protocol/device_orientation.rb"
      autoload :Emulation, "rammus/protocol/emulation.rb"
      autoload :HeadlessExperimental, "rammus/protocol/headless_experimental.rb"
      autoload :IO, "rammus/protocol/io.rb"
      autoload :IndexedDB, "rammus/protocol/indexed_db.rb"
      autoload :Input, "rammus/protocol/input.rb"
      autoload :Inspector, "rammus/protocol/inspector.rb"
      autoload :LayerTree, "rammus/protocol/layer_tree.rb"
      autoload :Log, "rammus/protocol/log.rb"
      autoload :Memory, "rammus/protocol/memory.rb"
      autoload :Network, "rammus/protocol/network.rb"
      autoload :Overlay, "rammus/protocol/overlay.rb"
      autoload :Page, "rammus/protocol/page.rb"
      autoload :Performance, "rammus/protocol/performance.rb"
      autoload :Security, "rammus/protocol/security.rb"
      autoload :ServiceWorker, "rammus/protocol/service_worker.rb"
      autoload :Storage, "rammus/protocol/storage.rb"
      autoload :SystemInfo, "rammus/protocol/system_info.rb"
      autoload :Target, "rammus/protocol/target.rb"
      autoload :Tethering, "rammus/protocol/tethering.rb"
      autoload :Tracing, "rammus/protocol/tracing.rb"
      autoload :Testing, "rammus/protocol/testing.rb"
      autoload :Fetch, "rammus/protocol/fetch.rb"
      autoload :Console, "rammus/protocol/console.rb"
      autoload :Debugger, "rammus/protocol/debugger.rb"
      autoload :HeapProfiler, "rammus/protocol/heap_profiler.rb"
      autoload :Profiler, "rammus/protocol/profiler.rb"
      autoload :Runtime, "rammus/protocol/runtime.rb"
      autoload :Schema, "rammus/protocol/schema.rb"
  end
end
