module Chromiebara
  module Protocol
      autoload :Accessibility, "chromiebara/protocol/accessibility.rb"
      autoload :Animation, "chromiebara/protocol/animation.rb"
      autoload :ApplicationCache, "chromiebara/protocol/application_cache.rb"
      autoload :Audits, "chromiebara/protocol/audits.rb"
      autoload :Browser, "chromiebara/protocol/browser.rb"
      autoload :CSS, "chromiebara/protocol/css.rb"
      autoload :CacheStorage, "chromiebara/protocol/cache_storage.rb"
      autoload :Cast, "chromiebara/protocol/cast.rb"
      autoload :DOM, "chromiebara/protocol/dom.rb"
      autoload :DOMDebugger, "chromiebara/protocol/dom_debugger.rb"
      autoload :DOMSnapshot, "chromiebara/protocol/dom_snapshot.rb"
      autoload :DOMStorage, "chromiebara/protocol/dom_storage.rb"
      autoload :Database, "chromiebara/protocol/database.rb"
      autoload :DeviceOrientation, "chromiebara/protocol/device_orientation.rb"
      autoload :Emulation, "chromiebara/protocol/emulation.rb"
      autoload :HeadlessExperimental, "chromiebara/protocol/headless_experimental.rb"
      autoload :IO, "chromiebara/protocol/io.rb"
      autoload :IndexedDB, "chromiebara/protocol/indexed_db.rb"
      autoload :Input, "chromiebara/protocol/input.rb"
      autoload :Inspector, "chromiebara/protocol/inspector.rb"
      autoload :LayerTree, "chromiebara/protocol/layer_tree.rb"
      autoload :Log, "chromiebara/protocol/log.rb"
      autoload :Memory, "chromiebara/protocol/memory.rb"
      autoload :Network, "chromiebara/protocol/network.rb"
      autoload :Overlay, "chromiebara/protocol/overlay.rb"
      autoload :Page, "chromiebara/protocol/page.rb"
      autoload :Performance, "chromiebara/protocol/performance.rb"
      autoload :Security, "chromiebara/protocol/security.rb"
      autoload :ServiceWorker, "chromiebara/protocol/service_worker.rb"
      autoload :Storage, "chromiebara/protocol/storage.rb"
      autoload :SystemInfo, "chromiebara/protocol/system_info.rb"
      autoload :Target, "chromiebara/protocol/target.rb"
      autoload :Tethering, "chromiebara/protocol/tethering.rb"
      autoload :Tracing, "chromiebara/protocol/tracing.rb"
      autoload :Testing, "chromiebara/protocol/testing.rb"
      autoload :Fetch, "chromiebara/protocol/fetch.rb"
      autoload :Console, "chromiebara/protocol/console.rb"
      autoload :Debugger, "chromiebara/protocol/debugger.rb"
      autoload :HeapProfiler, "chromiebara/protocol/heap_profiler.rb"
      autoload :Profiler, "chromiebara/protocol/profiler.rb"
      autoload :Runtime, "chromiebara/protocol/runtime.rb"
      autoload :Schema, "chromiebara/protocol/schema.rb"
  end
end
